@echo off
echo # Removing tnebes user if exists...
echo # Removing sbrc if exists...
echo # Creating tnebes user...
echo # Creating sbrc database...

psql -U "postgres" -d "postgres" -f "./init.sql"

